services:
  php-fpm:
    # Override for dev container usage
    command: sleep infinity
    volumes:
      - ../src:/var/www/html:cached
    environment:
      - TZ=UTC
    # Ensure the container stays running
    stdin_open: true
    tty: true

  nginx:
    volumes:
      - ../src:/var/www/html:cached
    environment:
      - NGINX_ERROR_LOG_LEVEL=debug
